CREATE TABLE CatBreeds(
	IdCatBreed INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(150) NOT NULL,
	Temperament VARCHAR(200) NOT NULL,
	Origin VARCHAR(200) NOT NULL,
	Description VARCHAR(500) NOT NULL,
	ImageURL VARCHAR(600) NOT NULL
)

CREATE TABLE Users(
	IdUser INT PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(100) NOT NULL,
	PasswordHash VARBINARY(256) NOT NULL, 
    Salt VARBINARY(128) NOT NULL
)


